### ISSUE TITLE
SSL SHA-1 issue.

### ISSUE THREAD

**Issue by lukevers** [AccelerateNetworks/acceleratenetworks.com#2]
Opening up the console I get a constant stream of these issues from [FirefoxDeveloperEdition](https://www.mozilla.org/en-US/firefox/developer/):

> This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1. [[Learn More]](https://developer.mozilla.org/en-US/docs/Security/Weak_Signature_Algorithm)

 You should probably use an SSL cert with something better than SHA-1.

**Comment by thefinn93** [comment]
[SSL Labs](https://www.ssllabs.com/ssltest/analyze.html?d=acceleratenetworks.com) sez we use SHA-2...

**Comment by lukevers** [comment]
OH! So it's talking about google.

**Comment by lukevers** [comment]
It should say "This site uses assets that use a SHA-1 Certificate" instead

**Comment by thefinn93** [comment]
Related: #3
