### ISSUE TITLE
3rd party assets

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/acceleratenetworks.com#3]
Lets host assets locally and not be leaking our visitor logs to Google and co

**Comment by lukevers** [comment]
Sounds good. It was just faster to use google fonts and everything while I was still building it.

**Comment by thefinn93** [comment]
Yeah for sure, no rush

**Comment by danry25** [comment]
Google is no longer used for maps in this repo (we replaced it with Mapbox [last year](https://github.com/AccelerateNetworks/acceleratenetworks.com/commit/2cc86be4b8965bf5cf6e2bed0f0868cc886fc5a5), here is [their privacy policy](https://www.mapbox.com/legal/privacy/)).

Let me know if their privacy policy concerns you, we could perhaps replace this with a static image instead, as scaling to different browser sizes with a static image and existing experience with Mapbox is why it was swapped in to replace Google Maps at the time.
