### ISSUE TITLE
https://billng.acceleratenetworks.com/ is down

### ISSUE THREAD

**Issue by uncheckederror** [AccelerateNetworks/acceleratenetworks.com#4]
[https://billng.acceleratenetworks.com/](https://billng.acceleratenetworks.com/)

DNS_PROBE_FINISHED_NXDOMAIN in Chrome Version 70.0.3538.102 (Official Build) (64-bit)

It would be nice if the "Login" button on the main page actually went somewhere.

**Comment by danry25** [comment]
This looks to be a link to our old billing platform, we handle invoices differently now. I will get the link changed to something useful...

**Comment by uncheckederror** [comment]
Is this issue resolved now?

**Comment by danry25** [comment]
I changed the link, but still have yet to rebrand the number search tool and set it up.

**Comment by uncheckederror** [comment]
This appears to be resolved as of now.
